name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build ./home-control-ui --file home-control-ui/Dockerfile --tag home-control-ui:$(date +%s)
        docker tag home-control-ui:$(date +%s) 192.168.1.20:8082/home-control-ui:$(date +%s)
        docker push 192.168.1.20:8082/home-control-ui:$(date +%s)
